apiVersion: v1
name: deployment
version: 1.0.0
description: The Universal Deployment Helm Chart
keywords:
  - deployment
  - helm
  - devops-nirvana
home: https://github.com/DevOps-Nirvana/Universal-Kubernetes-Helm-Charts
sources:
  - https://github.com/DevOps-Nirvana/Universal-Kubernetes-Helm-Charts/charts/deployment

