apiVersion: v1
name: cronjob-multi
version: 2.0.0
description: The Universal Cronjob Multi Helm Chart, to spin up many similar cronjobs
keywords:
  - cronjob
  - cronjob-multi
  - helm
  - devops-nirvana
